## Numpy Opreations



1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [63]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
import numpy as np
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


 Create a new array of shape 3 with random numbers between 0 and 1.

In [64]:
#Create a new array of shape 3 with random numbers between 0 and 1.
import numpy as np
randarr = np.random.rand(3)
print(randarr)

[0.45389938 0.31616821 0.14569883]


 Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:

o Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows

In [65]:
# Create a 2 dimensional array (2-D)
import numpy as np
twodimarr = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print(twodimarr)

# Slice the twoD array to get the first two rows
slicedarr = twodimarr[0:2]
print("\n", slicedarr)

# Similarily, slice the twoD array to get the last two rows
slicedtwoDrows = twodimarr[1:3]
print("\n", slicedtwoDrows)

[[10 20 45]
 [30 12 16]
 [42 17 56]]

 [[10 20 45]
 [30 12 16]]

 [[30 12 16]
 [42 17 56]]


. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, 
and split the arrays into smaller arrays.

In [66]:
import numpy as np
a1 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
a2 = np.array([[15, 25, 45], [35, 11, 26], [12, 27, 26]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

# Stack the arrays vertically
vertstack = np.vstack((a1, a2))
print("\n", vertstack)

# Stack the arrays horizontally
horzstack = np.hstack((a1, a2))
print("\n", horzstack)

# Spilt  the arrays
spiltarr = np.array_split(a1, 4)
print("\n", spiltarr)

a1:
[[10 20 45]
 [30 12 16]
 [42 17 56]]
a2:
[[15 25 45]
 [35 11 26]
 [12 27 26]]

 [[10 20 45]
 [30 12 16]
 [42 17 56]
 [15 25 45]
 [35 11 26]
 [12 27 26]]

 [[10 20 45 15 25 45]
 [30 12 16 35 11 26]
 [42 17 56 12 27 26]]

 [array([[10, 20, 45]]), array([[30, 12, 16]]), array([[42, 17, 56]]), array([], shape=(0, 3), dtype=int32)]


. Create two matrices 𝑋 = ([[5, 7, 2],[4, 5, 6],[7, 4 ,2]]), 𝑌 = ([[4, 2],[6, 2],[4, 2]]),
o Is it possible to multiply these matrices?
o Demonstrate the case when it is not possible to.


In [67]:
import numpy as np
X = np.array([[5, 7, 2], [4, 5,6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])
print(f'X:\n{X}')
print(f'Y:\n{Y}')

print("\n", np.matmul(X,Y))

X:
[[5 7 2]
 [4 5 6]
 [7 4 2]]
Y:
[[4 2]
 [6 2]
 [4 2]]

 [[70 28]
 [70 30]
 [60 26]]


Create two arrays, 𝑥 = ([2, −1, −8]) 𝑦 = ([3, 1, −2]),
o Find the Shape, Number of dimensions of vector x.
o Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions 
after reshaping y to a matrix of (3,1).


In [68]:
import numpy as np
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])
print(f'x:\n{x}')
print(f'y:\n{y}')

array_shape = x.shape
print("\n Array shape x:\n", array_shape)
print("\n Array Dimensions x:\n", x.ndim)

print( "\n Array Reshape x:\n", np.reshape(x, (3, 1)))
print( "\n Array Reshape y:\n", np.reshape(y, (3, 1)))
print("\n Array Dimensions y :\n", x.ndim)

x:
[ 2 -1 -8]
y:
[ 3  1 -2]

 Array shape x:
 (3,)

 Array Dimensions x:
 1

 Array Reshape x:
 [[ 2]
 [-1]
 [-8]]

 Array Reshape y:
 [[ 3]
 [ 1]
 [-2]]

 Array Dimensions y :
 1


. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 
matrix.


In [69]:
# Creating a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Demonstrating broadcasting with subtraction
subtracted_matrix = matrix - 2

# Demonstrating broadcasting with multiplication
multiplied_matrix = matrix * 3

# Displaying the original matrix and the results
print("Original Matrix:")
print(matrix)
print("\nSubtracted Matrix:")
print(subtracted_matrix)
print("\nMultiplied Matrix:")
print(multiplied_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtracted Matrix:
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

Multiplied Matrix:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


Part B- Linear Equations

Part B.1
1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [70]:

# Coefficient matrix
coeff_matrix = np.array([[4, 1, -2],
                        [2, -3, 2],
                        [1, 2, 3]])

# Right-hand side vector
rhs_vector = np.array([10, -4, 6])

# Calculate determinant
det_coeff_matrix = np.linalg.det(coeff_matrix)

print("Determinant of the coefficient matrix:", det_coeff_matrix)

if det_coeff_matrix != 0:
    # Non-singular system, unique solution exists
    solution = np.linalg.solve(coeff_matrix, rhs_vector)
    print("Solution of the system:", solution)
else:
    print("The system is singular, and the solution may not exist or may have infinitely many solutions.")

Determinant of the coefficient matrix: -70.00000000000003
Solution of the system: [ 1.8  2.4 -0.2]


Part B.2


1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [71]:
import numpy as np

# Coefficients matrix
coefficients_matrix_b2 = np.array([
    [2, -1, 3, 4],
    [4, -2, 6, 8],
    [3, 1, -2, 2],
    [1, 3, -4, 1]
])

# Constants vector
constants_vector_b2 = np.array([10, 20, 3, -1])

try:
    # Attempt to solve the system
    solution_b2 = np.linalg.solve(coefficients_matrix_b2, constants_vector_b2)
    print("Unique solution exists:")
    print("x =", solution_b2[0])
    print("y =", solution_b2[1])
    print("z =", solution_b2[2])
    print("w =", solution_b2[3])

except np.linalg.LinAlgError:
    print("The system is singular. It may have infinitely many solutions or no solution.")

The system is singular. It may have infinitely many solutions or no solution.
